steps:
  - id: 'create-repository'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: [
      'artifacts',
      'repositories',
      'create',
      'data-pipeline',
      '--repository-format=docker',
      '--location=us-central1',
      '--project=${PROJECT_ID}',
      '--description="Docker image for data ingestion and pipeline execution"' 
      ]
    allowFailure: true

  - id: 'build-docker-image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--network=cloudbuild',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/data-pipeline/latest',
      '-f',
      'Dockerfile',
      '.'
      ]

  - id: 'push-image-to-artifact-registry'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/data-pipeline/latest'
      ]
    waitFor: ['build-docker-image']

  - id: 'deploy-to-cloud-run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'beta',
      'run',
      'jobs',
      'update',
      'spotifyapp', 
      '--image',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/data-pipeline/latest',
      '--region', 'us-central1',
      '--task-timeout', '3600',
      '--max-retries', '1'
      ]
    waitFor: ['push-image-to-artifact-registry']
  
  - id: 'upload pyspark file to gcs'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gsutil
    args: [
      'cp',
      'spark_jobs/playback_pipeline.py',
      'gs://playback-history/pyspark_jobs/playback_pipeline.py'
      ]
  
  - id: 'schedule dataproc job'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args: [
      'scheduler',
      'jobs',
      'create',
      'http',
      'spotifyapp-playback-pipeline',
      '--schedule',
      '30 6 * * *',
      '--uri',
      'https://dataproc.googleapis.com/v1/projects/spotify-playback-history/regions/us-central1/workflowTemplates/spotify_workflow:instantiate?alt=json',
      '--http-method',
      'POST',
      '--location',
      'us-central1'
    ]
    allowFailure: true

  # - id: 'execute-cloud-run'
  #   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args: ['beta', 'run', 'jobs', 'execute',
  #         'spotifyapp',
  #         '--region', 'us-central1'
  #          ]
  #   waitFor: ['push-image-to-artifact-registry']    

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/data-pipeline/latest'